var = input("Digite um valor: ")
print(type(var))
print("É str",var.isalpha())
print("É numérico",var.isnumeric())
print("É alpha numérico",var.isalnum())
print("É decimal",var.isdecimal())
print("É inteiro",var.isdigit())
print("É espaço",var.isspace())
print("É maiúscula",var.isupper())
print("É minúsculas",var.islower())
print("É capitalizada",var.istitle())